# Generated by Django 4.1.2 on 2022-10-21 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость')),
                ('image', models.ImageField(upload_to='media/course_images/%Y/%m/%d', verbose_name='Обложка')),
                ('archive', models.FileField(upload_to='media/course_archives/%Y/%m/%d', verbose_name='Архив с курсом')),
                ('creating_date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('users', models.ManyToManyField(related_name='purchesed_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'courses',
            },
        ),
    ]
